[profile.default]
  evm_version = "cancun"
  ffi = true
  fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
  libs = ["lib"]
  optimizer_runs = 800
  out = "out"
  solc_version = "0.8.24"
  src = "src"
  via_ir = false

  # See more config options https://github.com/foundry-rs/foundry/tree/master/config
